# Generated by Django 4.2.6 on 2023-11-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=25)),
                ('xtra_cheese', models.CharField(max_length=10)),
                ('veg_nonveg', models.CharField(max_length=10)),
                ('pizza_base', models.CharField(max_length=10)),
            ],
        ),
    ]
