# Generated by Django 4.2.7 on 2023-11-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOpeningModel',
            fields=[
                ('count', models.IntegerField(auto_created=True)),
                ('refid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('DOR', models.DateField()),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
