# Generated by Django 4.2.6 on 2023-11-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formsfiels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.BigIntegerField()),
                ('Date', models.DateField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
