# Generated by Django 4.2.6 on 2023-11-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formsfiels',
            new_name='Formsfields',
        ),
    ]
