# Generated by Django 4.2.6 on 2023-11-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_formsfiels_formsfields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formsfields',
            new_name='FormsfieldsModel',
        ),
    ]
