# Generated by Django 4.2.7 on 2023-11-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_rename_formsfields_formsfieldsmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formsfieldsmodel",
            name="id",
        ),
        migrations.AlterField(
            model_name="formsfieldsmodel",
            name="Name",
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
