# Generated by Django 4.2.7 on 2023-11-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_remove_formsfieldsmodel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsfieldsmodel",
            name="acc_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formsfieldsmodel",
            name="Name",
            field=models.CharField(max_length=25),
        ),
    ]
