# Generated by Django 4.2.7 on 2023-11-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_formsfieldsmodel_acc_id_alter_formsfieldsmodel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsfieldsmodel",
            name="acc_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
