# Generated by Django 4.2.7 on 2023-11-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_formsfieldsmodel_acc_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsfieldsmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formsfieldsmodel",
            name="acc_id",
            field=models.IntegerField(),
        ),
    ]
