# Generated by Django 4.2.7 on 2023-11-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_formsfieldsmodel_id_alter_formsfieldsmodel_acc_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formsfieldsmodel",
            name="id",
        ),
        migrations.AlterField(
            model_name="formsfieldsmodel",
            name="acc_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
