# Generated by Django 4.2.6 on 2023-10-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaramodel',
            name='size',
            field=models.CharField(max_length=25),
        ),
    ]
