# Generated by Django 4.2.6 on 2023-11-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('age', models.BigIntegerField()),
                ('city', models.CharField(max_length=25)),
            ],
        ),
    ]
