# Generated by Django 4.2.6 on 2023-10-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanacc', models.IntegerField()),
                ('loanholdername', models.CharField(max_length=25)),
                ('loanamount', models.IntegerField()),
            ],
        ),
    ]
