# Generated by Django 4.2.6 on 2023-10-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_personaldetailsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanDetails',
            new_name='LoanDetailsModel',
        ),
    ]
