# Generated by Django 4.2.6 on 2023-10-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_rename_loandetails_loandetailsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_acc', models.IntegerField(max_length=12)),
                ('loan_holder', models.CharField(max_length=25)),
                ('loan_amount', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='LoanDetailsModel',
        ),
    ]
