# Generated by Django 4.2.6 on 2023-10-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loandetailmodel_delete_loandetailsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetailmodel',
            name='loan_acc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loandetailmodel',
            name='loan_amount',
            field=models.IntegerField(),
        ),
    ]
