# Generated by Django 4.2.6 on 2023-11-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanDetailsModel",
            fields=[
                ("loanid", models.IntegerField(primary_key=True, serialize=False)),
                ("loan_acc", models.IntegerField()),
                ("name", models.CharField(max_length=25)),
                ("age", models.IntegerField()),
                ("city", models.CharField(max_length=25)),
            ],
        ),
    ]
